services:
  langflow:
    image: langflowai/langflow:latest # or another version tag on https://hub.docker.com/r/langflowai/langflow
    pull_policy: always # set to 'always' when using 'latest' image
    ports:
      - "7860:7860"
    depends_on:
      - postgres
    environment:
      - LANGFLOW_DATABASE_URL=
      - LOG_PATH=/app/logs/langflow.log
      - LANGFLOW_LOG_FILE=langflow.log
      - LANGFLOW_LOG_LEVEL=DEBUG
      - LANGFLOW_STORE_ENVIRONMENT_VARIABLES=true
      - LANGFLOW_VARIABLES_TO_GET_FROM_ENVIRONMENT=OPENAI_API_KEY,GOOGLE_API_KEY, Composio_API_Key,ANTHROPIC_API_KEY
      #- LANGFUSE_SECRET_KEY=
      #- LANGFUSE_PUBLIC_KEY=
      #- LANGFUSE_HOST=https://cloud.langfuse.com
      - OPENAI_API_KEY=A
      - GOOGLE_API_KEY=
      - Composio_API_Key=
      - ANTHROPIC_API_KEY=

    volumes:
      - langflow114-data:/app/langflow
      - langflow114-logs:/app/logs # Volume for log storage
      - type: bind
        source: ./langflow-logs # <-- Source path on your host machine (relative to docker-compose.yml)
        target: /app/logs # <-- Target path inside container
        bind:
          create_host_path: true
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: langflow
      POSTGRES_PASSWORD: langflow
      POSTGRES_DB: langflow114
    ports:
      - "5432:5432"
    volumes:
      - langflow114-postgres:/var/lib/postgresql/data

volumes:
  langflow114-postgres:
  langflow114-data:
  langflow114-logs:


